services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_URL: mongodb://dev:dev@mongo

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: ${MONGODB_URI}
      ADMIN_SECRET: ${ADMIN_SECRET}
      GRECAPTCHA_SITE_KEY: ${GRECAPTCHA_SITE_KEY}
      GRECAPTCHA_SECRET_KEY: ${GRECAPTCHA_SECRET_KEY}
